/**
 * Regenerates common.generated.ts from common.txt (docs/BACKEND.md A12).
 *
 *   node src/lib/passwords/generate.mjs
 *
 * Keeps only the entries that could pass every other password rule: at least
 * 10 characters with a letter and a digit. The rules look up the *normalised*
 * copy of a password (NFKC, invisibles out, spaces collapsed, Western digits,
 * lower-case) and apply the length and letter+digit rules to that same copy,
 * so a password whose copy is a dropped entry is always refused by another
 * rule first — dropping it changes no answer, for any input. (The 72-byte rule
 * reads the password as typed, so it is deliberately not a filter here.)
 * `password.test.ts` proves the equivalence against the full list and fails if
 * this script and the checked-in module ever drift.
 *
 * The module is imported ONLY by the server-side check (`server.ts`) and by
 * the sign-up and reset forms — never by `src/lib/validation/**`, which every
 * client bundle reaches (docs/BACKEND.md A12 as amended, G-B1).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

/** Must match `commonCandidates` in password.test.ts. */
export function filterCommon(text) {
  const out = new Set();
  for (const line of text.split(/\r?\n/)) {
    const entry = line.trim().toLowerCase();
    if (
      [...entry].length >= 10 &&
      /\p{L}/u.test(entry) &&
      /\p{Nd}/u.test(entry)
    ) {
      out.add(entry);
    }
  }
  return [...out].sort();
}

const entries = filterCommon(readFileSync(join(here, "common.txt"), "utf8"));
const body = [
  "// GENERATED by src/lib/passwords/generate.mjs from common.txt — do not edit.",
  "// Only the entries that could pass every other password rule (docs/BACKEND.md A12).",
  "// Imported only by src/lib/passwords/server.ts and the sign-up/reset forms (G-B1).",
  "export const COMMON_PASSWORDS: ReadonlySet<string> = new Set([",
  ...entries.map((entry) => `  ${JSON.stringify(entry)},`),
  "]);",
  "",
].join("\n");
writeFileSync(join(here, "common.generated.ts"), body);
console.log(`common.generated.ts: ${entries.length} entries`);
